use_default_settings: true

general:
  debug: false
  instance_name: "Long Article Writer Search"
  privacypolicy_url: false
  donation_url: false
  contact_url: false
  enable_metrics: false

search:
  safe_search: 0
  autocomplete: ""
  default_lang: "en"
  ban_time_on_fail: 5
  max_ban_time_on_fail: 120
  formats:
    - html
    - json

server:
  port: 8080
  bind_address: "0.0.0.0"
  secret_key: "long-article-writer-secret-key-12345678"
  base_url: false
  image_proxy: false
  http_protocol_version: "1.0"
  method: "POST"
  default_http_headers:
    X-Content-Type-Options: nosniff
    X-XSS-Protection: 1; mode=block
    X-Download-Options: noopen
    X-Robots-Tag: noindex, nofollow
    Referrer-Policy: no-referrer

ui:
  static_use_hash: false
  default_locale: "en"
  query_in_title: false
  infinite_scroll: false
  center_alignment: false
  cache_url: undef
  default_theme: simple
  theme_args:
    simple_style: auto

# Enabled engines
engines:
  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    timeout: 3.0
    disabled: false

  - name: google
    engine: google
    shortcut: go
    timeout: 3.0
    disabled: false

  - name: bing
    engine: bing
    shortcut: bi
    timeout: 3.0
    disabled: false

  - name: wikipedia
    engine: wikipedia
    shortcut: wp
    timeout: 3.0
    disabled: false